### ISSUE TITLE
The Kermits 126 - Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [amita-roy/Task-Todo#3]
Wonderful work, Amita. I'm not surprised it was approved so swiftly. The code organisation is excellent and the project is really nice to read through, which was helped by your use of jQuery. Really great work Amita, onwards and upwards.

Best project ever

**Comment by amita-roy** [comment]
Thank you so much team for encouraging me to work hard and smart 😃.
